import type { Metadata } from "next";
import { Jua } from "next/font/google";
import "./globals.css";
// @import url("@mdi/font/css/materialdesignicons.css");

const juaSans = Jua({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${juaSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
